尝试完善了 组件 Switch
sumsc-caa/pandora-2023-questionnaire pull request #4
Opened 2023-05-11 14:49 UTC by SuperTeea

按照查的资料（没多少用上）和代码模板里的一些提示尝试完善了一下 Switch.
~~也算是尝试吃螃蟹~~
如果有什么不对请赐教 AWA

2023-05-11 16:23 UTC, Furffico requested changes
很感谢您能参加本次活动。这作为您的第一次Pull Request已经很不错啦~
把3处问题改完之后直接在这里更新PR，然后就可以给您通过了。

2023-05-11 16:23 UTC, Furffico commented on components/Switch.py
> +        return dic
可能是我没说清楚，这里要返回的是从表单中提取到的这个字段的值。
switch只有开（`True`）和关（`False`）两种状态。查询[相关文档](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/checkbox)可知，在这里当switch开启时，表单里的值为`on`（或是value属性的值），否则表单里不存在这个值，所以这里可以这样写：
```python
data = formdata.get(name, None)
return bool(data)
```

2023-05-11 16:24 UTC, Furffico requested changes
很感谢您能参加本次活动。这作为您的第一次Pull Request已经很不错啦~
把3处问题改完之后直接在这里更新PR，然后就可以给您通过了。

2023-05-11 16:36 UTC, Furffico commented on components/Switch.py
> +        return dic
关于为什么会查到这个文档：
1. 虽然这个组件长得像个开关，但是它在提交表单时的行为是由`type`属性决定的，在这里就是`checkbox`；
2. [mdn web docs](https://developer.mozilla.org/zh-CN/) 算是前端比较权威的文档，链接在本项目的README.md可以找到；
3. 所以就在mdn web docs（或者直接使用搜索引擎搜索）查找input元素在`type="checkbox"`时的行为，就找到了这个页面。

2023-05-12 11:43 UTC, SuperTeea commented
Thanks.

2023-05-12 11:44 UTC, Furffico reviewed
Well done!

2023-05-12 11:44 UTC, Furffico approved these changes
Well done!

2023-05-12 11:45 UTC, merged

2023-05-12 12:25 UTC, DanteIoVeYou commented
Good job